components:
  schemas:
    Barra:
      description: Objeto de origem do Sistema XPTO, usado para Fins X,Y e Z  com
        o objetivo de resolver algo
      properties:
        Id:
          type: string
        Nome:
          type: string
        Numero:
          type: integer
        agente:
          type: string
      type: object
    Dominio:
      description: Objeto de origem do Sistema XPTO, usado para Fins X,Y e Z  com
        o objetivo de resolver algo
      properties:
        Descricao:
          type: integer
        Identificador:
          type: string
      type: object
    Erro:
      description: schema of error return data.
      properties:
        code:
          format: int32
          type: integer
        fields:
          type: string
        message:
          type: string
      type: object
    ObjetosDisponiveis:
      items:
        type: string
      type: array
info:
  title: Modelo Canonico Elétrico
  version: 1.0.0
openapi: 3.0.1
paths:
  /:
    get:
      operationId: getObjetosDisponiveis
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjetosDisponiveis'
          description: Ok
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
          description: Erro
servers:
- url: http://localhost:10010/CanonicoEletrico/v1
