openapi: 3.0.1
info:
  title: Modelo Canonico Elétrico
  version: 1.0.0
servers:
- url: http://localhost:10010/CanonicoEletrico/v1
paths:
  /:
    get:
      operationId: getObjetosDisponiveis
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjetosDisponiveis'
        default:
          description: Erro
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
components:
  schemas:
    Barra:
      type: object
      description: Objeto de origem do Sistema XPTO, usado para Fins X,Y e Z  com o objetivo de resolver algo
      properties:
        Id:
          type: string
        Numero:
          type: integer
        Nome:
          type: string
        agente:
          type: string
    Dominio:
      type: object
      description: Objeto de origem do Sistema XPTO, usado para Fins X,Y e Z  com o objetivo de resolver algo
      properties:
        Identificador:
          type: string
        Descricao:
          type: integer
    ObjetosDisponiveis:
        type: array
        items:
          type: string
    Erro:
      type: object
      description: schema of error return data.
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string